Repository Quaran-Team/server-EarthBnB, pull requests merged in 2020-09, with the labels that each got.

#46 basic routes and seed data for first 4 listings for photos component
  EarthBnB/src/main/java/com/Earthbb/PhotosBWL/PhotoController.java
  EarthBnB/src/main/java/com/Earthbb/PhotosBWL/PhotoData.java
  EarthBnB/src/main/java/com/Earthbb/PhotosBWL/PhotoRepository.java
  EarthBnB/src/main/resources/db/migration/V5__photos_seed_data.sql
Labels: feature

#53 all routes work tested in postman
  EarthBnB/src/main/java/com/Earthbb/PhotosBWL/PhotoData.java
Labels: chore, t.x-small

#54 Routing for the main table and the addition of the maps table
  EarthBnB/src/main/java/com/Earthbb/MPTS/Mpts.java
  EarthBnB/src/main/java/com/Earthbb/MPTS/MptsController.java
  EarthBnB/src/main/java/com/Earthbb/Map/Map.java
  EarthBnB/src/main/java/com/Earthbb/Map/MapController.java
  EarthBnB/src/main/java/com/Earthbb/Map/MapRepository.java
Labels: chore

#61 migration name conflict fix
  EarthBnB/src/main/resources/db/migration/V9__cohostdata.sql
Labels: bug, chore

#62 Feature/reviews connection
  EarthBnB/src/main/resources/db/migration/V7__reviews_seed.sql
Labels: chore, t.x-small

#65 Feature/reviews connection
  EarthBnB/src/main/java/com/Earthbb/Reviews/ReviewsController.java
  EarthBnB/src/main/java/com/Earthbb/Reviews/ReviewsRepository.java
  EarthBnB/src/main/resources/db/migration/V7__reviews_seed.sql
Labels: t.small

#76 Feature/things to do data
  EarthBnB/src/main/java/com/Earthbb/TTD/Ttd.java
  EarthBnB/src/main/resources/db/migration/V11__todo_table.sql
  EarthBnB/src/main/resources/db/migration/V12__todo_seed_data.sql
  EarthBnB/src/main/resources/db/migration/V13__sleepingarrs.sql
Labels: feature

#78 fixed price data type and added more listings changed a few pics
  EarthBnB/src/main/java/com/Earthbb/TTD/Ttd.java
  EarthBnB/src/main/resources/db/migration/V11__todo_table.sql
  EarthBnB/src/main/resources/db/migration/V12__todo_seed_data.sql
Labels: chore

#81 even seed data for all states
  EarthBnB/src/main/resources/db/migration/V12__todo_seed_data.sql
Labels: chore
